/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accountSol from "./Account.sol";
export type { accountSol };
import type * as accountManagerSol from "./AccountManager.sol";
export type { accountManagerSol };
import type * as lib from "./lib";
export type { lib };
import type * as proxy from "./proxy";
export type { proxy };
import type * as test from "./test";
export type { test };
