/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testOtpSol from "./TestOTP.sol";
export type { testOtpSol };
export type { TestAccount } from "./TestAccount";
export type { TestAccountTarget } from "./TestAccountTarget";
export type { TestBase64 } from "./TestBase64";
export type { TestJWT } from "./TestJWT";
export type { TestMakeJSON } from "./TestMakeJSON";
export type { TestP256R1 } from "./TestP256R1";
export type { TestWebAuthN } from "./TestWebAuthN";
