/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TestAccountTargetInterface extends Interface {
  getFunction(nameOrSignature: "example" | "exampleView"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ExampleEvent"): EventFragment;

  encodeFunctionData(functionFragment: "example", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "exampleView",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "example", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "exampleView",
    data: BytesLike
  ): Result;
}

export namespace ExampleEventEvent {
  export type InputTuple = [arg0: AddressLike, arg1: AddressLike];
  export type OutputTuple = [arg0: string, arg1: string];
  export interface OutputObject {
    arg0: string;
    arg1: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TestAccountTarget extends BaseContract {
  connect(runner?: ContractRunner | null): TestAccountTarget;
  waitForDeployment(): Promise<this>;

  interface: TestAccountTargetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  example: TypedContractMethod<[], [void], "nonpayable">;

  exampleView: TypedContractMethod<[], [[string, string]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "example"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "exampleView"
  ): TypedContractMethod<[], [[string, string]], "view">;

  getEvent(
    key: "ExampleEvent"
  ): TypedContractEvent<
    ExampleEventEvent.InputTuple,
    ExampleEventEvent.OutputTuple,
    ExampleEventEvent.OutputObject
  >;

  filters: {
    "ExampleEvent(address,address)": TypedContractEvent<
      ExampleEventEvent.InputTuple,
      ExampleEventEvent.OutputTuple,
      ExampleEventEvent.OutputObject
    >;
    ExampleEvent: TypedContractEvent<
      ExampleEventEvent.InputTuple,
      ExampleEventEvent.OutputTuple,
      ExampleEventEvent.OutputObject
    >;
  };
}
