/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MakeJSON {
  export type KeyValueStruct = { t: BigNumberish; k: string; v: string };

  export type KeyValueStructOutput = [t: bigint, k: string, v: string] & {
    t: bigint;
    k: string;
    v: string;
  };
}

export interface TestHelperInterface extends Interface {
  getFunction(
    nameOrSignature: "createChallengeBase64" | "createDigest"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createChallengeBase64",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createDigest",
    values: [BytesLike, MakeJSON.KeyValueStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "createChallengeBase64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDigest",
    data: BytesLike
  ): Result;
}

export interface TestHelper extends BaseContract {
  connect(runner?: ContractRunner | null): TestHelper;
  waitForDeployment(): Promise<this>;

  interface: TestHelperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createChallengeBase64: TypedContractMethod<
    [in_data: BytesLike, personalization: BytesLike],
    [string],
    "view"
  >;

  createDigest: TypedContractMethod<
    [authenticatorData: BytesLike, clientDataTokens: MakeJSON.KeyValueStruct[]],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createChallengeBase64"
  ): TypedContractMethod<
    [in_data: BytesLike, personalization: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createDigest"
  ): TypedContractMethod<
    [authenticatorData: BytesLike, clientDataTokens: MakeJSON.KeyValueStruct[]],
    [string],
    "view"
  >;

  filters: {};
}
