/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TestBase64Interface extends Interface {
  getFunction(nameOrSignature: "testDecode" | "testEncode"): FunctionFragment;

  encodeFunctionData(functionFragment: "testDecode", values: [string]): string;
  encodeFunctionData(
    functionFragment: "testEncode",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "testDecode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "testEncode", data: BytesLike): Result;
}

export interface TestBase64 extends BaseContract {
  connect(runner?: ContractRunner | null): TestBase64;
  waitForDeployment(): Promise<this>;

  interface: TestBase64Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  testDecode: TypedContractMethod<[input: string], [string], "view">;

  testEncode: TypedContractMethod<[input: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "testDecode"
  ): TypedContractMethod<[input: string], [string], "view">;
  getFunction(
    nameOrSignature: "testEncode"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;

  filters: {};
}
