/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface TestOTPSHA256Interface extends Interface {
  getFunction(nameOrSignature: "HMAC" | "HOTP" | "TOTP"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "HMAC",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "HOTP",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "TOTP",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "HMAC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "HOTP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TOTP", data: BytesLike): Result;
}

export interface TestOTPSHA256 extends BaseContract {
  connect(runner?: ContractRunner | null): TestOTPSHA256;
  waitForDeployment(): Promise<this>;

  interface: TestOTPSHA256Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  HMAC: TypedContractMethod<
    [key: BytesLike, message: BytesLike],
    [string],
    "view"
  >;

  HOTP: TypedContractMethod<[K: BytesLike, C: BigNumberish], [bigint], "view">;

  TOTP: TypedContractMethod<
    [key: BytesLike, time_step: BigNumberish, when: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "HMAC"
  ): TypedContractMethod<
    [key: BytesLike, message: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "HOTP"
  ): TypedContractMethod<[K: BytesLike, C: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTP"
  ): TypedContractMethod<
    [key: BytesLike, time_step: BigNumberish, when: BigNumberish],
    [bigint],
    "view"
  >;

  filters: {};
}
