/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WebAuthNExample } from "./WebAuthNExample";
export type { WebAuthNExampleStorage } from "./WebAuthNExampleStorage";
