/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  AccountManagerStorage,
  AccountManagerStorageInterface,
} from "../../../contracts/AccountManager.sol/AccountManagerStorage";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "dataHash",
        type: "bytes32",
      },
    ],
    name: "GaslessTransaction",
    type: "event",
  },
  {
    inputs: [],
    name: "devAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "gaspayingAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "personalization",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "salt",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "signer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610147908161001c8239f35b600080fdfe608080604052600436101561001357600080fd5b600090813560e01c908163108a5eee146100e857508063238ac933146100bf5780633ad10ef614610096578063bfa0b133146100785763fd24dc1e1461005857600080fd5b346100755780600319360112610075576020600854604051908152f35b80fd5b50346100755780600319360112610075576020600354604051908152f35b5034610075578060031936011261007557600a546040516001600160a01b039091168152602090f35b50346100755780600319360112610075576009546040516001600160a01b039091168152602090f35b90503461010d578160031936011261010d576006546001600160a01b03168152602090f35b5080fdfea264697066735822122021702b8ca55ef3367891d0dd7c64056548d00687ace33ea35cfc035a35e5621764736f6c63430008150033";

type AccountManagerStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AccountManagerStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AccountManagerStorage__factory extends ContractFactory {
  constructor(...args: AccountManagerStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AccountManagerStorage & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): AccountManagerStorage__factory {
    return super.connect(runner) as AccountManagerStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AccountManagerStorageInterface {
    return new Interface(_abi) as AccountManagerStorageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AccountManagerStorage {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AccountManagerStorage;
  }
}
