/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SECP256R1Interface extends Interface {
  getFunction(nameOrSignature: "Gx" | "Gy" | "isOnCurve"): FunctionFragment;

  encodeFunctionData(functionFragment: "Gx", values?: undefined): string;
  encodeFunctionData(functionFragment: "Gy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isOnCurve",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "Gx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Gy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOnCurve", data: BytesLike): Result;
}

export interface SECP256R1 extends BaseContract {
  connect(runner?: ContractRunner | null): SECP256R1;
  waitForDeployment(): Promise<this>;

  interface: SECP256R1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  Gx: TypedContractMethod<[], [bigint], "view">;

  Gy: TypedContractMethod<[], [bigint], "view">;

  isOnCurve: TypedContractMethod<
    [x: BigNumberish, y: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(nameOrSignature: "Gx"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "Gy"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isOnCurve"
  ): TypedContractMethod<[x: BigNumberish, y: BigNumberish], [boolean], "view">;

  filters: {};
}
